project:
  type: book

book:
  title: "SWAMP Strategy"
  author: "CA Surface Water Ambient Monitoring Program (SWAMP)"
  date: "2024-03-01"
  search: true
  repo-url: https://github.com/CAWaterBoardDataCenter/swamp-strategy
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
  
    - index.qmd
    - about-swamp.qmd
    - contribute.qmd
    
  sidebar:
    style: "docked"
    logo: "images/swamp-iq-logos.png"
    # type: "light"
    # background: "#002151"
    # foreground: "light"
    border: true

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

# comments:
#   hypothesis: true