# Workplan

This Workplan for the SWAMP Statewide [Bioassessment Monitoring Program](https://www.waterboards.ca.gov/water_issues/programs/swamp/bioassessment/) describes strategic projects and actions the Progam intends to implement to advance SWAMP's four thematic priorities and vision.

All of the Program's priority projects and associated actions are categorized under SWWAMP's four strategic themes: Program Management, Monitoring, Data Quality & Management, Communication & Engagement. For more information on each of these themes, see [SWAMP Priorities (2025-2030)](https://cawaterboarddatacenter.github.io/swamp-strategy/prioriites.html).

Key: \* = highest-priority actions for the current strategic planning period (2025 - 2030)

## Program Management & Coordination

### Project 1: 1 sentence description of project

Task/Action 1.1: 1-2 sentence description of task

## Monitoring & Assessment

### Project 2: 1 sentence description of project

Task/Action 2.1: 1-2 sentence description of task

## Data Quality & Management

### Project 3: 1 sentence description of project

Task/Action 3.1: 1-2 sentence description of task

## Communication & Engagement

### Project 4: 1 sentence description of project

Task/Action 4.1: 1-2 sentence description of task
